-- ============================================================
-- SIGUMI BACKOFFICE — Tracking Pendaki Migration
-- Jalankan di Supabase SQL Editor (Settings → SQL Editor)
-- ============================================================

-- 1. Pastikan extension postgis aktif untuk tipe data geography (jika belum)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create Table hiking_sessions
CREATE TABLE IF NOT EXISTS public.hiking_sessions (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  status text not null default 'active'::text,
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone null,
  last_point_at timestamp with time zone null,
  last_latitude double precision null,
  last_longitude double precision null,
  distance_km double precision not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint hiking_sessions_pkey primary key (id),
  constraint hiking_sessions_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint hiking_sessions_distance_km_check check ((distance_km >= (0)::double precision)),
  constraint hiking_sessions_status_check check (
    (
      status = any (
        array[
          'active'::text,
          'completed'::text,
          'cancelled'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_hiking_sessions_user_started on public.hiking_sessions using btree (user_id, started_at desc) TABLESPACE pg_default;

create index IF not exists idx_hiking_sessions_active on public.hiking_sessions using btree (status) TABLESPACE pg_default
where
  (status = 'active'::text);

-- 3. Create Table hiking_track_points
CREATE TABLE IF NOT EXISTS public.hiking_track_points (
  id bigint generated by default as identity not null,
  session_id uuid not null,
  recorded_at timestamp with time zone not null default now(),
  latitude double precision not null,
  longitude double precision not null,
  accuracy_meters double precision null,
  location geography GENERATED ALWAYS as (
    (
      st_setsrid (
        st_makepoint (longitude, latitude),
        4326
      )
    )::geography
  ) STORED null,
  constraint hiking_track_points_pkey primary key (id),
  constraint hiking_track_points_session_id_fkey foreign KEY (session_id) references hiking_sessions (id) on delete CASCADE,
  constraint hiking_track_points_latitude_check check (
    (
      (latitude >= ('-90'::integer)::double precision)
      and (latitude <= (90)::double precision)
    )
  ),
  constraint hiking_track_points_longitude_check check (
    (
      (longitude >= ('-180'::integer)::double precision)
      and (longitude <= (180)::double precision)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_hiking_track_points_session_time on public.hiking_track_points using btree (session_id, recorded_at) TABLESPACE pg_default;

create index IF not exists idx_hiking_track_points_location on public.hiking_track_points using gist (location) TABLESPACE pg_default;

-- 4. Set RLS (Row Level Security) - Opsional sesuai kebutuhan
-- ALTER TABLE public.hiking_sessions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.hiking_track_points ENABLE ROW LEVEL SECURITY;
